type: regex
path:
  - {{dirs.src}}
  - babel.config.js
data:
  - find: |
      /^(.*)(presets)(.*)(babel-preset-expo)(.*)$/m
    replace: |
      $1$2$3$4$5$1plugins: ["nativewind/babel"],
    already: |
      nativewind/babel
